version: '3'
services:
  omni_api:
    build:
      context: api
      dockerfile: Dockerfile
    depends_on:
      - omni_postgres
#      - omni_core
      - omni_engine
      - omni_redis
    links:
      - omni_postgres
#      - omni_core
      - omni_redis
    ports:
      - "4005:80"
    labels:
      com.datadoghq.ad.logs: '[{"source": "omni-docker", "service": "omni-api"}]'

  omni_explorer:
    build:
      context: explorer
      dockerfile: Dockerfile
    depends_on:
      - omni_api
    links:
      - omni_api
    ports:
      - "4006:3000"
    labels:
      com.datadoghq.ad.logs: '[{"source": "omni-docker", "service": "omni-explorer"}]'
  omni_engine:
    build:
      context: engine
      dockerfile: Dockerfile
    depends_on:
      - omni_postgres
 #     - omni_core
      - omni_redis
    links:
      - omni_postgres
  #    - omni_core
      - omni_redis
    environment:
      FLYWAY_PLACEHOLDERS_OMNIAPIPASSWORD: omniapipass
      FLYWAY_PLACEHOLDERS_OMNIENGINEPASSWORD: omnienginepass
      PGUSER: postgres
      PGPASSWORD: postgresspass
      PGHOST: omni_postgres
      PGPORT: 5432
      OMNIDB_DATABASE: omni
      NETWORK: mainnet
    labels:
      com.datadoghq.ad.logs: '[{"source": "omni-docker", "service": "omni-engine"}]'

  omni_postgres:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgresspass
      POSTGRES_DB: omni
    labels:
      com.datadoghq.ad.logs: '[{"source": "omni-docker", "service": "omni-postgres"}]'
  omni_redis:
    image: redis:alpine
    restart: always
    labels:
      com.datadoghq.ad.logs: '[{"source": "omni-docker", "service": "omni-redis"}]'

volumes:
  pgdata:
